package com.example.noignore.data.mission

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity for persistent adaptive daily missions generated by Aiko based on learner weaknesses,
 * due FSRS reviews, and available study time (including emergency 5-minute low-friction mode).
 */
@Entity(tableName = "daily_missions")
data class DailyMissionEntity(
    @PrimaryKey
    val dateString: String, // "yyyy-MM-dd"
    val missionJson: String, // Serialized mission task breakdown
    val isFiveMinuteMode: Boolean = false,
    val isCompleted: Boolean = false,
    val completedAtMs: Long? = null
)
